/// Commands contributed by the host application's native menu system.
enum PlatformCommand {
  newWorkspace,
  openWorkspace,
  openReaderSources,
  openSampleLibrary,
  saveWorkspace,
  saveWorkspaceAs,
  addFolder,
  addMarkdown,
  openAppearance,
  findDocument,
  searchLibrary,
  toggleShelf,
  toggleOutline,
  copySelection,
  selectAllText,
  enlargeText,
  shrinkText,
  resetText,
  showKeyboardShortcuts,
  openSupport,
  openPrivacy,
  showLicenses,
}
